version: '3.8'

services:
  frontend:
    image: zbarbe-frontend:debug-v1
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_BASE=http://localhost:9090/api
        - VITE_API_URL=http://localhost:9090/api
    environment:
      - VITE_API_BASE=http://localhost:9090/api
      - VITE_API_URL=http://localhost:9090/api
      - NODE_ENV=development
    ports:
      - "8080:80"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    image: zbarbe-backend:debug-v1
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=development
      - PORT=9090
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Mfcd62!!Mfcd62!!SaaS
      - JWT_SECRET=your-secret-key-change-in-production
      - CORS_ORIGIN=http://localhost:8080
      - FRONTEND_URL=http://localhost:8080
    ports:
      - "9090:9090"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: overlay
    attachable: true