version: '3.8'

services:
  frontend:
    image: zbarbe-frontend:${TAG:-latest}
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zbarbe-network

  backend:
    image: zbarbe-backend:${TAG:-latest}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=5.78.113.107
      - DB_PORT=5432
      - DB_NAME=barber_system
      - DB_USER=postgres
      - DB_PASSWORD=Mfcd62!!Mfcd62!!SaaS
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zbarbe-network

networks:
  zbarbe-network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local